[package]
name = "Rustody"
version = "1.2.1"
edition = "2021"
license-file = "LICENSE"
description = "Split BD rapsody fastq files into sample specific fastq files"
homepage = "https://github.com/stela2502/split2samples"
repository = "https://github.com/stela2502/split2samples"
readme = "README.md"

[dependencies]
ahash = "0.7.6"
anyhow = "1.0.66"
needletail = "0.4"
clap = { version = "3.0.14", features = ["derive"] }
csv = "1.1"
serde = { version="1.0.103", features = ["derive"] }
flate2 = "1.0.24"
kmers = { git="https://github.com/COMBINE-lab/kmers" }
glob = "0.3.0"
regex = "1"
this = { path = "this" }
indicatif = {version = "*", features = ["rayon"]}